name: Run with environment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    env:
      MY_ENV: Yes

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run test
        run: |
          python main.py
